markdown: kramdown

url: https://larkin269.github.io/  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /fikpages/      # place folder name if the site is served in a subfolder

# Title of the Site
title: '#Fik 握手会'
# Description of the Site
description: アイドル

# SASS
sass:
  sass_dir: _sass
  style: expanded

gems:
  - jekyll-feed