markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: '#Fik 握手会'
# Description of the Site
description: アイドル

# SASS
sass:
  sass_dir: _sass
  style: expanded

gems:
  - jekyll-feed